#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")/.."
# Reviewed native-pixel selections; never includes opaque stone frame 6 or wrong-facing north poses.
java tools/PackFrames.java 32 32 8 -1 assets/effects/ichor_idle.png docs/art-review/immersion-40/ichor-loop/frame-1.png docs/art-review/immersion-40/ichor-loop/frame-2.png docs/art-review/immersion-40/ichor-loop/frame-3.png docs/art-review/immersion-40/ichor-loop/frame-4.png docs/art-review/immersion-40/ichor-loop/frame-5.png docs/art-review/immersion-40/ichor-loop/frame-6.png docs/art-review/immersion-40/ichor-loop/frame-7.png docs/art-review/immersion-40/ichor-loop/frame-8.png
java tools/PackFrames.java 32 32 8 -1 assets/effects/ichor_pickup.png docs/art-review/immersion-40/ichor-absorb/frame-0.png docs/art-review/immersion-40/ichor-absorb/frame-2.png docs/art-review/immersion-40/ichor-absorb/frame-4.png docs/art-review/immersion-40/ichor-absorb/frame-7.png docs/art-review/immersion-40/ichor-absorb/frame-8.png docs/art-review/immersion-40/ichor-absorb/frame-10.png docs/art-review/immersion-40/ichor-absorb/frame-14.png docs/art-review/immersion-40/ichor-absorb/frame-16.png
java tools/PackFrames.java 48 48 8 -1 assets/effects/slime_hurt.png docs/art-review/immersion-40/slime-hurt-burst/frame-0.png docs/art-review/immersion-40/slime-hurt-burst/frame-1.png docs/art-review/immersion-40/slime-hurt-burst/frame-3.png docs/art-review/immersion-40/slime-hurt-burst/frame-5.png docs/art-review/immersion-40/slime-hurt-burst/frame-7.png docs/art-review/immersion-40/slime-hurt-burst/frame-10.png docs/art-review/immersion-40/slime-hurt-burst/frame-13.png docs/art-review/immersion-40/slime-hurt-burst/frame-16.png docs/art-review/immersion-40/slime-hurt-shear/frame-0.png docs/art-review/immersion-40/slime-hurt-shear/frame-2.png docs/art-review/immersion-40/slime-hurt-shear/frame-4.png docs/art-review/immersion-40/slime-hurt-shear/frame-6.png docs/art-review/immersion-40/slime-hurt-shear/frame-8.png docs/art-review/immersion-40/slime-hurt-shear/frame-10.png docs/art-review/immersion-40/slime-hurt-shear/frame-13.png docs/art-review/immersion-40/slime-hurt-shear/frame-16.png
java tools/PackFrames.java 48 48 8 -1 assets/effects/armor_sparks.png docs/art-review/immersion-40/blade-hit-burst/frame-0.png docs/art-review/immersion-40/blade-hit-burst/frame-1.png docs/art-review/immersion-40/blade-hit-burst/frame-4.png docs/art-review/immersion-40/blade-hit-burst/frame-5.png docs/art-review/immersion-40/blade-hit-burst/frame-6.png docs/art-review/immersion-40/blade-hit-burst/frame-7.png docs/art-review/immersion-40/blade-hit-burst/frame-8.png docs/art-review/immersion-40/blade-hit-burst/frame-9.png docs/art-review/immersion-40/armor-deflect/frame-0.png docs/art-review/immersion-40/armor-deflect/frame-2.png docs/art-review/immersion-40/armor-deflect/frame-4.png docs/art-review/immersion-40/armor-deflect/frame-6.png docs/art-review/immersion-40/armor-deflect/frame-8.png docs/art-review/immersion-40/armor-deflect/frame-10.png docs/art-review/immersion-40/armor-deflect/frame-13.png docs/art-review/immersion-40/armor-deflect/frame-15.png
java tools/PackFrames.java 32 32 8 -1 assets/effects/spit_orb.png docs/art-review/immersion-40/spit-orb-loop/frame-1.png docs/art-review/immersion-40/spit-orb-loop/frame-2.png docs/art-review/immersion-40/spit-orb-loop/frame-3.png docs/art-review/immersion-40/spit-orb-loop/frame-4.png docs/art-review/immersion-40/spit-orb-loop/frame-5.png docs/art-review/immersion-40/spit-orb-loop/frame-6.png docs/art-review/immersion-40/spit-orb-loop/frame-7.png docs/art-review/immersion-40/spit-orb-loop/frame-8.png
java tools/PackFrames.java 48 48 8 -1 assets/effects/spit_impact.png docs/art-review/immersion-40/spit-impact-burst/frame-0.png docs/art-review/immersion-40/spit-impact-burst/frame-1.png docs/art-review/immersion-40/spit-impact-burst/frame-3.png docs/art-review/immersion-40/spit-impact-burst/frame-4.png docs/art-review/immersion-40/spit-impact-burst/frame-5.png docs/art-review/immersion-40/spit-impact-burst/frame-10.png docs/art-review/immersion-40/spit-impact-burst/frame-13.png docs/art-review/immersion-40/spit-impact-burst/frame-16.png
java tools/PackFrames.java 32 32 8 -1 assets/effects/stone_chips.png docs/art-review/immersion-40/stone-scatter/frame-0.png docs/art-review/immersion-40/stone-scatter/frame-2.png docs/art-review/immersion-40/stone-scatter/frame-4.png docs/art-review/immersion-40/stone-scatter/frame-7.png docs/art-review/immersion-40/stone-scatter/frame-9.png docs/art-review/immersion-40/stone-scatter/frame-11.png docs/art-review/immersion-40/stone-scatter/frame-13.png docs/art-review/immersion-40/stone-scatter/frame-14.png
java tools/PackFrames.java 48 48 8 47 docs/art-review/immersion-40/spitter-south-attack.png docs/art-review/immersion-40/spitter-cast-south/frame-0.png docs/art-review/immersion-40/spitter-cast-south/frame-1.png docs/art-review/immersion-40/spitter-cast-south/frame-2.png docs/art-review/immersion-40/spitter-cast-south/frame-3.png docs/art-review/immersion-40/spitter-cast-south/frame-4.png docs/art-review/immersion-40/spitter-cast-south/frame-5.png docs/art-review/immersion-40/spitter-cast-south/frame-15.png docs/art-review/immersion-40/spitter-cast-south/frame-16.png
java tools/PackFrames.java 48 48 4 47 docs/art-review/immersion-40/spitter-south-walk.png docs/art-review/immersion-40/spitter-cast-south/frame-0.png docs/art-review/immersion-40/spitter-cast-south/frame-1.png docs/art-review/immersion-40/spitter-cast-south/frame-2.png docs/art-review/immersion-40/spitter-cast-south/frame-1.png
java tools/PackFrames.java 48 48 8 47 docs/art-review/immersion-40/spitter-west-attack.png docs/art-review/immersion-40/spitter-cast-west/frame-0.png docs/art-review/immersion-40/spitter-cast-west/frame-1.png docs/art-review/immersion-40/spitter-cast-west/frame-3.png docs/art-review/immersion-40/spitter-cast-west/frame-5.png docs/art-review/immersion-40/spitter-cast-west/frame-6.png docs/art-review/immersion-40/spitter-cast-west/frame-7.png docs/art-review/immersion-40/spitter-cast-west/frame-15.png docs/art-review/immersion-40/spitter-cast-west/frame-16.png
java tools/PackFrames.java 48 48 4 47 docs/art-review/immersion-40/spitter-west-walk.png docs/art-review/immersion-40/spitter-cast-west/frame-0.png docs/art-review/immersion-40/spitter-cast-west/frame-1.png docs/art-review/immersion-40/spitter-cast-west/frame-3.png docs/art-review/immersion-40/spitter-cast-west/frame-1.png
java tools/PackFrames.java 48 48 8 43 docs/art-review/immersion-40/spitter-north-attack.png docs/art-review/immersion-40/spitter-cast-north/frame-3.png docs/art-review/immersion-40/spitter-cast-north/frame-4.png docs/art-review/immersion-40/spitter-cast-north/frame-5.png docs/art-review/immersion-40/spitter-cast-north/frame-6.png docs/art-review/immersion-40/spitter-cast-north/frame-14.png docs/art-review/immersion-40/spitter-cast-north/frame-15.png docs/art-review/immersion-40/spitter-cast-north/frame-16.png docs/art-review/immersion-40/spitter-cast-north/frame-4.png
java tools/PackFrames.java 48 48 4 43 docs/art-review/immersion-40/spitter-north-walk.png docs/art-review/immersion-40/spitter-cast-north/frame-3.png docs/art-review/immersion-40/spitter-cast-north/frame-4.png docs/art-review/immersion-40/spitter-cast-north/frame-5.png docs/art-review/immersion-40/spitter-cast-north/frame-4.png
java tools/PackFrames.java 384 48 1 -1 assets/characters/wisp/spitter_attack.png docs/art-review/immersion-40/spitter-south-attack.png docs/art-review/immersion-40/spitter-west-attack.png docs/art-review/immersion-40/spitter-north-attack.png
java tools/PackFrames.java 192 48 1 -1 assets/characters/wisp/spitter_walk.png docs/art-review/immersion-40/spitter-south-walk.png docs/art-review/immersion-40/spitter-west-walk.png docs/art-review/immersion-40/spitter-north-walk.png
